name: CI

on:
  pull_request:
    branches: [master]

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '10.0.0'

      - name: Get Node.js Version
        id: node_version
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Print "which node"
        run: |
          which node

      - run: npm install -g yarn

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-${{ steps.node_version.outputs.version }}-${{ hashFiles('./yarn.lock') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn test
